// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {domain} from '../models';

export function AppInfo():Promise<domain.AppInfo>;

export function CreateProfile(arg1:domain.ProfileInput):Promise<domain.Profile>;

export function DeleteModrinthMod(arg1:string,arg2:string):Promise<domain.ModrinthDeleteResult>;

export function DeleteModrinthModFiles(arg1:string,arg2:string,arg3:Array<string>):Promise<domain.ModrinthDeleteResult>;

export function DeleteProfile(arg1:string):Promise<void>;

export function DeleteProfileMod(arg1:string,arg2:string):Promise<domain.ModList>;

export function ExportModrinthModpack(arg1:string):Promise<domain.ModpackExportResult>;

export function GetAccount():Promise<domain.AccountConfig>;

export function GetCachedVersionCatalog():Promise<domain.VersionCatalog>;

export function GetModrinthProject(arg1:string):Promise<domain.ModrinthProject>;

export function GetProfileJavaRuntime(arg1:string):Promise<domain.ProfileJavaRuntime>;

export function GetSettings():Promise<domain.Settings>;

export function ImportModrinthModpack():Promise<domain.ModpackImportResult>;

export function ImportProfileMod(arg1:string):Promise<domain.ModList>;

export function InstallJava(arg1:number):Promise<domain.JavaStatus>;

export function InstallModrinthMod(arg1:string,arg2:string):Promise<domain.ModrinthInstallResult>;

export function InstallModrinthModFiles(arg1:string,arg2:string,arg3:Array<string>):Promise<domain.ModrinthInstallResult>;

export function InstallModrinthModVersionFiles(arg1:string,arg2:string,arg3:string,arg4:Array<string>):Promise<domain.ModrinthInstallResult>;

export function InstallProfile(arg1:string):Promise<domain.Profile>;

export function LaunchProfile(arg1:string):Promise<domain.LaunchState>;

export function ListFabricLoaderVersions():Promise<Array<domain.VersionOption>>;

export function ListForgeLoaderVersions():Promise<Array<domain.VersionOption>>;

export function ListInstalledModrinthProjects(arg1:string):Promise<Array<string>>;

export function ListMinecraftVersions():Promise<Array<domain.VersionOption>>;

export function ListModrinthProjectVersions(arg1:string,arg2:string):Promise<Array<domain.ModrinthVersion>>;

export function ListModrinthUpdates(arg1:string):Promise<Array<domain.ModrinthUpdatePlan>>;

export function ListNeoForgeLoaderVersions():Promise<Array<domain.VersionOption>>;

export function ListProfileGameLogs(arg1:string):Promise<domain.GameLogList>;

export function ListProfileMods(arg1:string):Promise<domain.ModList>;

export function ListProfiles():Promise<domain.ProfileList>;

export function ListQuiltLoaderVersions():Promise<Array<domain.VersionOption>>;

export function OpenProfileLogsFolder(arg1:string):Promise<void>;

export function OpenProfileModsFolder(arg1:string):Promise<void>;

export function PlanModrinthDelete(arg1:string,arg2:string):Promise<domain.ModrinthDeletePlan>;

export function PlanModrinthInstall(arg1:string,arg2:string):Promise<domain.ModrinthInstallPlan>;

export function PlanModrinthInstallVersion(arg1:string,arg2:string,arg3:string):Promise<domain.ModrinthInstallPlan>;

export function PlanModrinthUpdate(arg1:string,arg2:string):Promise<domain.ModrinthUpdatePlan>;

export function PlanModrinthUpdateFile(arg1:string,arg2:string):Promise<domain.ModrinthUpdatePlan>;

export function PlanModrinthUpdateVersion(arg1:string,arg2:string,arg3:string):Promise<domain.ModrinthUpdatePlan>;

export function ReadProfileGameLog(arg1:string,arg2:string):Promise<domain.GameLogContent>;

export function RefreshVersionCatalog():Promise<domain.VersionCatalog>;

export function RepairProfile(arg1:string):Promise<domain.Profile>;

export function SaveAccount(arg1:domain.AccountConfig):Promise<domain.AccountConfig>;

export function SaveSettings(arg1:domain.Settings):Promise<domain.Settings>;

export function SearchModrinthMods(arg1:string,arg2:string):Promise<domain.ModrinthSearchResult>;

export function SelectProfile(arg1:string):Promise<domain.ProfileList>;

export function SetProfileModEnabled(arg1:string,arg2:string,arg3:boolean):Promise<domain.ModList>;

export function UpdateModrinthModFile(arg1:string,arg2:string,arg3:Array<string>):Promise<domain.ModrinthUpdateResult>;

export function UpdateModrinthModFiles(arg1:string,arg2:string,arg3:Array<string>):Promise<domain.ModrinthUpdateResult>;

export function UpdateModrinthModVersionFiles(arg1:string,arg2:string,arg3:string,arg4:Array<string>):Promise<domain.ModrinthUpdateResult>;

export function UpdateProfile(arg1:string,arg2:domain.ProfileInput):Promise<domain.Profile>;

export function ValidateJava():Promise<domain.JavaStatus>;
