// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function AppInfo() {
  return window['go']['main']['App']['AppInfo']();
}

export function CreateProfile(arg1) {
  return window['go']['main']['App']['CreateProfile'](arg1);
}

export function DeleteModrinthMod(arg1, arg2) {
  return window['go']['main']['App']['DeleteModrinthMod'](arg1, arg2);
}

export function DeleteModrinthModFiles(arg1, arg2, arg3) {
  return window['go']['main']['App']['DeleteModrinthModFiles'](arg1, arg2, arg3);
}

export function DeleteProfile(arg1) {
  return window['go']['main']['App']['DeleteProfile'](arg1);
}

export function DeleteProfileMod(arg1, arg2) {
  return window['go']['main']['App']['DeleteProfileMod'](arg1, arg2);
}

export function ExportModrinthModpack(arg1) {
  return window['go']['main']['App']['ExportModrinthModpack'](arg1);
}

export function GetAccount() {
  return window['go']['main']['App']['GetAccount']();
}

export function GetCachedVersionCatalog() {
  return window['go']['main']['App']['GetCachedVersionCatalog']();
}

export function GetModrinthProject(arg1) {
  return window['go']['main']['App']['GetModrinthProject'](arg1);
}

export function GetProfileJavaRuntime(arg1) {
  return window['go']['main']['App']['GetProfileJavaRuntime'](arg1);
}

export function GetSettings() {
  return window['go']['main']['App']['GetSettings']();
}

export function ImportModrinthModpack() {
  return window['go']['main']['App']['ImportModrinthModpack']();
}

export function ImportProfileMod(arg1) {
  return window['go']['main']['App']['ImportProfileMod'](arg1);
}

export function InstallJava(arg1) {
  return window['go']['main']['App']['InstallJava'](arg1);
}

export function InstallModrinthMod(arg1, arg2) {
  return window['go']['main']['App']['InstallModrinthMod'](arg1, arg2);
}

export function InstallModrinthModFiles(arg1, arg2, arg3) {
  return window['go']['main']['App']['InstallModrinthModFiles'](arg1, arg2, arg3);
}

export function InstallModrinthModVersionFiles(arg1, arg2, arg3, arg4) {
  return window['go']['main']['App']['InstallModrinthModVersionFiles'](arg1, arg2, arg3, arg4);
}

export function InstallProfile(arg1) {
  return window['go']['main']['App']['InstallProfile'](arg1);
}

export function LaunchProfile(arg1) {
  return window['go']['main']['App']['LaunchProfile'](arg1);
}

export function ListFabricLoaderVersions() {
  return window['go']['main']['App']['ListFabricLoaderVersions']();
}

export function ListForgeLoaderVersions() {
  return window['go']['main']['App']['ListForgeLoaderVersions']();
}

export function ListInstalledModrinthProjects(arg1) {
  return window['go']['main']['App']['ListInstalledModrinthProjects'](arg1);
}

export function ListMinecraftVersions() {
  return window['go']['main']['App']['ListMinecraftVersions']();
}

export function ListModrinthProjectVersions(arg1, arg2) {
  return window['go']['main']['App']['ListModrinthProjectVersions'](arg1, arg2);
}

export function ListModrinthUpdates(arg1) {
  return window['go']['main']['App']['ListModrinthUpdates'](arg1);
}

export function ListNeoForgeLoaderVersions() {
  return window['go']['main']['App']['ListNeoForgeLoaderVersions']();
}

export function ListProfileGameLogs(arg1) {
  return window['go']['main']['App']['ListProfileGameLogs'](arg1);
}

export function ListProfileMods(arg1) {
  return window['go']['main']['App']['ListProfileMods'](arg1);
}

export function ListProfiles() {
  return window['go']['main']['App']['ListProfiles']();
}

export function ListQuiltLoaderVersions() {
  return window['go']['main']['App']['ListQuiltLoaderVersions']();
}

export function OpenProfileLogsFolder(arg1) {
  return window['go']['main']['App']['OpenProfileLogsFolder'](arg1);
}

export function OpenProfileModsFolder(arg1) {
  return window['go']['main']['App']['OpenProfileModsFolder'](arg1);
}

export function PlanModrinthDelete(arg1, arg2) {
  return window['go']['main']['App']['PlanModrinthDelete'](arg1, arg2);
}

export function PlanModrinthInstall(arg1, arg2) {
  return window['go']['main']['App']['PlanModrinthInstall'](arg1, arg2);
}

export function PlanModrinthInstallVersion(arg1, arg2, arg3) {
  return window['go']['main']['App']['PlanModrinthInstallVersion'](arg1, arg2, arg3);
}

export function PlanModrinthUpdate(arg1, arg2) {
  return window['go']['main']['App']['PlanModrinthUpdate'](arg1, arg2);
}

export function PlanModrinthUpdateFile(arg1, arg2) {
  return window['go']['main']['App']['PlanModrinthUpdateFile'](arg1, arg2);
}

export function PlanModrinthUpdateVersion(arg1, arg2, arg3) {
  return window['go']['main']['App']['PlanModrinthUpdateVersion'](arg1, arg2, arg3);
}

export function ReadProfileGameLog(arg1, arg2) {
  return window['go']['main']['App']['ReadProfileGameLog'](arg1, arg2);
}

export function RefreshVersionCatalog() {
  return window['go']['main']['App']['RefreshVersionCatalog']();
}

export function RepairProfile(arg1) {
  return window['go']['main']['App']['RepairProfile'](arg1);
}

export function SaveAccount(arg1) {
  return window['go']['main']['App']['SaveAccount'](arg1);
}

export function SaveSettings(arg1) {
  return window['go']['main']['App']['SaveSettings'](arg1);
}

export function SearchModrinthMods(arg1, arg2) {
  return window['go']['main']['App']['SearchModrinthMods'](arg1, arg2);
}

export function SelectProfile(arg1) {
  return window['go']['main']['App']['SelectProfile'](arg1);
}

export function SetProfileModEnabled(arg1, arg2, arg3) {
  return window['go']['main']['App']['SetProfileModEnabled'](arg1, arg2, arg3);
}

export function UpdateModrinthModFile(arg1, arg2, arg3) {
  return window['go']['main']['App']['UpdateModrinthModFile'](arg1, arg2, arg3);
}

export function UpdateModrinthModFiles(arg1, arg2, arg3) {
  return window['go']['main']['App']['UpdateModrinthModFiles'](arg1, arg2, arg3);
}

export function UpdateModrinthModVersionFiles(arg1, arg2, arg3, arg4) {
  return window['go']['main']['App']['UpdateModrinthModVersionFiles'](arg1, arg2, arg3, arg4);
}

export function UpdateProfile(arg1, arg2) {
  return window['go']['main']['App']['UpdateProfile'](arg1, arg2);
}

export function ValidateJava() {
  return window['go']['main']['App']['ValidateJava']();
}
